-- Create proposals table
CREATE TABLE proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    "upVotes" INTEGER DEFAULT 0,
    "downVotes" INTEGER DEFAULT 0,
    "favorArguments" TEXT,
    "againstArguments" TEXT,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;

/*
-- Create policy for authenticated users to view all proposals
create policy "Authenticated users can view proposals"
  on proposals
  for select
  to authenticated
  using (true);
*/

create policy "Anonymous users can view proposals"
  on proposals 
  for select
  to public
  using (true);

-- Create policy for users to insert their own proposals
create policy "Users can create their own proposals"
  on proposals
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Create policy for users to update their own proposals
create policy "Users can update their own proposals"
  on proposals
  for update
  to authenticated
  using (auth.uid() = user_id);

-- Create policy for users to delete their own proposals
create policy "Users can delete their own proposals"
  on proposals
  for delete
  to authenticated
  using (auth.uid() = user_id);